name: LockMyStuff
main: mohagames\lockmystuff\Main
version: 0.2.1
api: 3.6.2
author: Mohagames205
description: Lock your stuff like never before!
website: https://github.com/Mohagames205/LockMyStuff

commands:
  lock:
    description: Lock a door!
    usage: /lock <doorname>
    permission: lms.lock
  unlock:
    description: Remove the lock from a door!
    usage: /unlock <doorname (optional)>
    permission: lms.unlock
  makekey:
    description: Make a key!
    usage: /makekey <doorname>
    permission: lms.makekey


permissions:
  lms:
    children:
      lms.lock:
        description: Allows the user to lock a door.
        default: OP
      lms.unlock:
        description: Allows the user to use the /unlock command.
        default: OP
      lms.makekey:
        description: Allows the user to make a key for any door.
        default: OP
      lms.break:
        description: Allows the user to break a locked door.
        default: OP