name: LockMyStuff
main: mohagames\lockmystuff\Main
version: 1.0.0
api: 3.0.0
author: Mohagames205
description: Lock your stuff like never before!
website: https://github.com/Mohagames205/LockMyStuff

commands:
  lock:
    description: Lock a door!
    usage: /lock <doorname>
    permission: lms.lock
  unlock:
    description: Remove the lock from a door!
    usage: /unlock <doorname (optional)>
    permission: lms.unlock
  makekey:
    description: Make a key!
    usage: /makekey <doorname>
    permission: lms.makekey
  lockedinfo:
    description: Gives info aboutt the touched locked item
    permission: lms.lockedinfo

permissions:
  lms:
    children:
      lms.lock:
        description: Allows the user to lock a door.
        default: op
      lms.unlock:
        description: Allows the user to use the /unlock command.
        default: op
      lms.makekey:
        description: Allows the user to make a key for any door.
        default: op
      lms.break:
        description: Allows the user to break a locked door.
        default: op
      lms.bypass:
        description: This allows the user to open every door
        default: op
      lms.lockedinfo:
        description: This allows the user to use the lockedinfo command
        default: true